name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          gcc -Wall -Wextra 01/gcd_iterative.c
          gcc -Wall -Wextra 01/gcd_recursive.c
