name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - run: gcc -Wall -Wextra 01/gcd_iterative.c
      - run: gcc -Wall -Wextra 01/gcd_recursive.c
