name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: gcc -Wall -Wextra -Werror ./01/gcd_iterative.c
      - run: gcc -Wall -Wextra -Werror ./01/gcd_recursive.c
      - run: gcc -Wall -Wextra -Werror ./02/linear_search.c
      - run: gcc -Wall -Wextra -Werror ./02/binary_search.c
      - run: gcc -Wall -Wextra -Werror ./03/array.c
      - run: gcc -Wall -Wextra -Werror ./03/linear_list.c
